### ISSUE TITLE
services misturadas com factories

### ISSUE THREAD

**Issue by DylanGuedes** [mdsgpp2016/frontend#2]
o arquivo services.js além de estar abrigando as services (ele deveria servir só de "callback", deveria ser criado uma pasta para as services e nela estar a service de injeção de profile, como foi feito com as controllers), está também abrigando factories (tambem acho que a mesma abordagem deva acontecer para as factories: criar um factories.js, e uma pasta de factories)

**Comment by vital-edu** [comment]
A Issue é a mesma da #22
