### ISSUE TITLE
US08 - Imagem do Facebook na API

### ISSUE THREAD

**Issue by vital-edu** [mdsgpp2016/frontend#23]
Eu, como desenvolvedor, desejo conseguir gravar a imagem do Facebook na API para que o cliente não precise fazer requisições ao Facebook após a criação do usuário.

**Comment by miguelpimentel** [comment]
Vital, pelo que eu sei o Vitor já fez isso. Só não sei as partes das
requisições.

Em 19 de maio de 2016 12:32, Eduardo Vital <notifications@github.com>
escreveu:
