### ISSUE TITLE
S01US12 - Entrar em uma carona

### ISSUE THREAD

**Issue by gutioliveira** [mdsgpp2016/frontend#30]
Eu,  como passageiro,  desejo entrar em uma carona existente para poder participar da viagem.

Critérios de aceitação:
A partir da tela de detalhes de uma carona.
Deve ser possível entrar na carona escolhida. [ ]
Não deve ser possível entrar na própria carona. [X]
Só deve ser possível entrar em uma carona uma vez. [ ]
No detalhamento de uma carona, deve ser possível visualizar a lista de passageiros e o motorista. [X]
Ao fazer parte de uma carona, deve ser atualizado o número de vagas dessa carona. [ ]
Não deve ser possível entrar mais pessoas que o limite da carona. [X]

CRITÉRIO REMOVIDO:
Deve haver a possibilidade de recusar pessoas na carona.

**Comment by DylanGuedes** [comment]
Essa história era inicialmente da Sprint 1, mas foi adiada por conta de pré-requisitos, e agora será feita na Sprint 3. O nome não foi alterado. A pontuação passou de 5 para 8 pontos.
