### ISSUE TITLE
S04US19 - Testes funcionais

### ISSUE THREAD

**Issue by wiltonsr** [mdsgpp2016/frontend#60]
Eu, como desenvolvedor, desejo que a aplicação possua uma suíte de teste funcionais (automatizada).

Critérios de aceitação:
Configurar o ambiente de testes.
Testar o logar com facebook.
Testar o manter (criar e editar) carona.
Testar o ver caronas.
Testar o manter veículo.

**Comment by danmoura17** [comment]
Terminamos os testes que faltavam
